### ISSUE TITLE
FastMM4-AVX 1.06: AV in Delphi 10.4.2

### ISSUE THREAD

**Issue by MaxTerentiev** [pleriche/FastMM4#86]
Empty app fails to run with AV with latest FastMM4-AVX version ! X32 build works but x64 fails.

**Comment by maximmasiutin** [comment]
How can I reproduce it? I've tried under 64-bit (both Release and Debug) with default conditional defines, and it works.

**Comment by MaxTerentiev** [comment]
Hi,

Attached AV error, debugger screenshot with line number and also example project for reproducing problem.

[FastMM-AVX Bug.zip](https://github.com/pleriche/FastMM4/files/6634371/FastMM-AVX.Bug.zip)

![AV_Error](https://user-images.githubusercontent.com/15716038/121596616-50622f00-ca48-11eb-95f0-6ba859f40346.jpg)
![Debugger_Break](https://user-images.githubusercontent.com/15716038/121596621-51935c00-ca48-11eb-8c5d-4f747a0e458c.jpg)

**Comment by MaxTerentiev** [comment]
Hi Maxim,

 

I was sent example project to issue thread on github.

 

---
With best regards, Max Terentiev.
Business Software Products.
AMS Development Team.
***@***.***

**Comment by maximmasiutin** [comment]
Thank you very much, I will take care of this in a couple of days.

**Comment by maximmasiutin** [comment]
Can you please, just for test, define an alignment of 32 bytes? Just try the following directive
```
{$define Align32Bytes}
```
(or add to the IDE options).

Please also try to align by 16 bytes as well (Align16Bytes). So we will know for sure what is the reason. The `vmodqa` instructions generates an access violation when the data is not aligned, however, there may be other reasons. And I have tested mainly on a CPU that supports the "Fast Short REP MOVSB CPU" (FSRM) feature, so it probably didn't use the AVX copy routines at all because the FSRM is more efficient.

**Comment by MaxTerentiev** [comment]
Hi,

 

I tried both {$define Align16Bytes} and then {$define Align32Bytes}

in Fastmm4Options.inc each time clean & rebuild projects but got same error in both cases !

Debugger stops on same source line 4056

 

---
With best regards, Max Terentiev.
Business Software Products.
AMS Development Team.
***@***.***

**Comment by maximmasiutin** [comment]
Thank you, I have just fixed it. Could you please check!?

**Comment by maximmasiutin** [comment]
Could you please close this issue here as I have configured the FastMM4-AVX to allow creating issues.

**Comment by MaxTerentiev** [comment]
I check with default Options.inc and It's worked now ! Thank you very much !
