### ISSUE TITLE
The new version no longer compiles in Delphi 4.

### ISSUE THREAD

**Issue by 120m4n** [pleriche/FastMM4#87]
I have tried compiling the new version on Delphi 4 (Client / Server) and it doesn't work due to the added changes.

Version 4.992 works without problems.

**Comment by pleriche** [comment]
Thank you for the feedback. Admittedly I did not test with Delphi 4. What is the compiler error message?

**Comment by the-Arioch** [comment]
Maybe you have to add ^ before .UnitName in the end

Afterall classic Pascal requires explicit pointers dereference, it was some
Delphi version that relaxed the rules and added on a guess dereferencing

All in all you have to split this complex line into a chain of simple lines
using temporary variables, so that each line only has one expression in it
( varN := varM operator varK; ).
And then see which exactly operation produces the error


>

**Comment by 120m4n** [comment]
thanks for the directions. I could already solve adding using:


      LClassInfoByte1 := {$ifdef PByteIsPAnsiChar}Byte{$endif}(PByte(LClassInfoPByte + 1)^);
      Inc(LClassInfoPByte, 2);
      Inc(LClassInfoPByte, LClassInfoByte1);
      LClassData := PClassData(LClassInfoPByte);
      UnitName := @(LClassData^.UnitName);
      FirstUnitNameChar := @UnitName^[1];
